name: Remote Desktop Access
on: [workflow_dispatch]

jobs:
  remote-desktop:
    runs-on: ubuntu-latest
    steps:
    - name: Install Xfce and VNC
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y xfce4 tightvncserver

    - name: Set VNC Password
      run: |
        mkdir -p ~/.vnc
        echo "${{ secrets.VNC_PASSWORD }}" | vncpasswd -f > ~/.vnc/passwd
        chmod 600 ~/.vnc/passwd

    - name: Start VNC Server
      run: |
        vncserver :1 -geometry 1280x800 -depth 24 -localhost
        DISPLAY=:1 xfce4-session &

    - name: Expose port with localhost.run
      run: |
        echo "Starting SSH tunnel..."
        ssh -o StrictHostKeyChecking=no -R 5901:localhost:5901 nokey@localhost.run > ssh.log 2>&1 &
        
        echo "Waiting for tunnel (up to 40 seconds)..."
        for i in {1..40}; do
          if grep -q "lhr.life" ssh.log; then
            break
          fi
          sleep 1
        done
        
        echo "=== CONNECTION INFO ==="
        TCP_URL=$(grep -oE '[a-z0-9]+\.lhr\.life' ssh.log | head -1)
        echo "VNC Server: ${TCP_URL}:5901"
        echo "Password: ${{ secrets.VNC_PASSWORD }}"
        echo "======================="
        
        sleep 3600  # Keep alive for 1 hour
